### ISSUE TITLE
a-tag's target attribute is not functional

### ISSUE THREAD

**Issue by Jinjinov** [tryphotino/photino.NET#110]
Links work normally on Windows and Linux but `<a href="http://blazor.net">About</a>` does nothing on macOS

Steps to reproduce:

1. open https://github.com/tryphotino/photino.Blazor/tree/master/Samples/Photino.Blazor.Sample on macOS
2. build and run
3. click on the `About` link

**Comment by philippjbauer** [comment]
Currently the about link in the sample app has the `target="_blank"` attribute. This would either open a new tab or window depending on the browser configuration. Since the webview implementation used in Photino is leaving this kind of behavior to the software that implements it, nothing happens when the attribute is specified Removing the attribute opens the link in the current window on all platforms as expected.

If you (or anyone else) wish to open a new Photino window when a link with the `target` attribute is clicked, you could for example intercept the click with Javascript, send the URL through IPC to the underlying C# program and spawn a new window with the URL.

@MikeYeager @ottodobretsberger we might want to think about adding this as default behavior of Photino
