### ISSUE TITLE
(React) samples out of date and are not working unless you update Photino.NET to v1.1.5

### ISSUE THREAD

**Issue by Zaid-Ajaj** [tryphotino/photino.NET#19]
Hello there, I am really interested in this project and tried out the samples. However, I wasn't able to run the samples unless I updated Photino.NET to v1.1.5 and even then it automatically started installing "Microsoft Edge WebView2" on its own (without even asking first) when I am on Windows 10 (Home) and do have Microsoft edge on it

Another issue I found is that the window freezes when I try to exit it

![photino](https://user-images.githubusercontent.com/13316248/110642939-d3f35200-81b3-11eb-84ec-37821226e790.gif)

**Comment by Zaid-Ajaj** [comment]
>  it automatically started installing "Microsoft Edge WebView2" on its own (without even asking first) when I am on Windows 10 (Home) and do have Microsoft edge on it

Wouldn't it be much better during development if the framework starts to look for _some_ available chromium instance (like an already installed chrome) on the machine and fallback to it when that specific Edge version isn't installed?

**Comment by philippjbauer** [comment]
Hi @Zaid-Ajaj!

Thank you for taking the time to write this up and point it out to us.

We have released updated samples today. The closing issue was addressed in the v1.1.6 update of Photino.NET.
You can find them in the now public [Photino.Samples](https://github.com/tryphotino/photino.Samples) repository.

The VS and .NET CLI templates will follow soon.

Thank you for the input on the WebView installation process. We have to determine a way to streamline the process. If it turns out to rely on an installed application we'll consider it.

Best, P
