### ISSUE TITLE
How to dynamically execute JavaScript and Intercept & obtain the response information for a specified URL

### ISSUE THREAD

**Issue by Fsystem** [tryphotino/photino.NET#192]
I am migrating from WebView2 to Photino.NET and have encountered two missing features.
1.Dynamically execute a JavaScript script and retrieve the return value in C#
2.Intercept and obtain the response information for a specified URL, with the ability to rewrite the response information.

**Comment by philippjbauer** [comment]
1. You can use the `window.external.sendMessage` function in Javascript to send data to C#, you can also use the window.SendWebMessage in C# to send messages to Javascript. You will have to create appropriate handlers on either side to handle the messages you send.

2. Can you elaborate what exactly you're trying to do here and perhaps provide an example?

**Comment by pryvyd9** [comment]
is there an example how to use `window.external.sendMessage`? Because it doesn't seem to work.

**Comment by MikeYeager** [comment]
Closed due to inactivity.

**Comment by pha3z** [comment]
I haven't seen this addressed anywhere.  This issue came up for me on Google.

I think the original poster is referring to this feature in Webview2:
https://learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/javascript

Its an extremely handy feature because it means you can point the webview2 at any webpage, wait for the page to load, and then execute arbitrary javascript by injecting it from .NET.

My understanding is that Photino does not currently support arbitrary javascript execution.  Instead, you have to load up a page with javascript already in it or you have to build the HTML with javascript and inject together into the view.  So you basically have to bootstrap the page with your own javascript handler so you can send messages to that handler. This is quite limiting if the user's objective is to load an arbitrary webpage and then inject javascript for immediate execution. Is there a workaround?
