### ISSUE TITLE
Cannot start window in a separate Task

### ISSUE THREAD

**Issue by Zaid-Ajaj** [tryphotino/photino.NET#21]
I am trying out Photino in combination with a web server where I run the webserver and the phonito window in separate threads. I consistently get blank pages when running the window on a separate thread:
### Works
```cs
[STAThread]
static void Main(string[] args)
{
    var window = new PhotinoNET.PhotinoWindow("HelloWorldReact App");
    window.Center().LoadRawString("<h1>Hello from C#</h1>");
    window.WaitForClose();
}
```
### Doesn't work
```cs
[STAThread]
static async Task Main(string[] args)
{
    await Task.Run(() =>
    {
        var window = new PhotinoNET.PhotinoWindow("HelloWorldReact App");
        window.Center().LoadRawString("<h1>Hello from C#</h1>");
        window.WaitForClose();
    });
}
```

Using Windows 10 (Home)
Photino.NET v1.1.6

**Comment by MikeYeager** [comment]
Not sure why you would want to use this scenario. There are Samples for running WebAPI and gRPC using .Async in the main program in order to do something similar. Running a completely separate web server process could involve a lot of unknowns and we'd need a lot more info on the scenario you're creating including things like which web server it is, if you're trying to use https, etc.

**Comment by Zaid-Ajaj** [comment]
My scenario is to embed a web server alongside the window and build a single page application running inside the window. During development, I would have `webpack-dev-server` running `http://localhost:8080` and the AspNet core backend running `http://localhost:5000` like you would build any Web API + SPA. The window running alongside the web server would either `.Load(new Uri("http://localhost:8080"))` during development or load the the root of the embedded web app after publishing. 

> There are Samples for running WebAPI and gRPC using .Async in the main program in order to do something similar. 

I saw that one but I  am using [Saturn](https://github.com/SaturnFramework/Saturn) which is a functional web framework built on top of ASP.NET Core for F# apps but it doesn't have an asynchronous `Start` method. Only synchronous:
```fs
// Saturn app in F#
let application = .... // IHostBuilder 
Saturn.run(application) // void
``` 
Which is a blocking operation, hence why I want to run them in separate threads

**Comment by philippjbauer** [comment]
On macOS it appears to crash because of a threading issue. We will open an issue in the Photino.Native repository.

```bash
photino.Samples/Photino.HelloPhotino.NET on  master [$!] via .NET 5.0.100 took 1m 46s 
➜ dotnet run
2021-03-11 12:39:40.085 dotnet[21661:7723684] WARNING: NSWindow drag regions should only be invalidated on the Main Thread! This will throw an exception in the future. Called from (
        0   AppKit                              0x00007fff22f0e47f -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 352
        1   AppKit                              0x00007fff22ef9121 -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 1375
        2   AppKit                              0x00007fff22ef8bbb -[NSWindow initWithContentRect:styleMask:backing:defer:] + 42
        3   Photino.Native.dylib                0x000000010f93e997 _ZN7PhotinoC2EPcPS_PFvS0_Ebiiii + 295
        4   Photino.Native.dylib                0x000000010f93eb6c _ZN7PhotinoC1EPcPS_PFvS0_Ebiiii + 124
        5   Photino.Native.dylib                0x000000010f9408d8 Photino_ctor + 152
```

**Comment by MikeYeager** [comment]
WOW, this has been quite interesting to learn about. The following link describes the issue and why this doesn't work - along with some suggestions for work-arounds:

https://stackoverflow.com/questions/47553489/set-apartmentstate-for-async-void-main 

If you add this code to the Main() method of a new Console app, you'll get a better idea of what's happening:
```
var t = Thread.CurrentThread;
Console.WriteLine($"Thread [{t.ManagedThreadId}] ApartmentState: {t.GetApartmentState()}  IsBackground: {t.IsBackground}  IsThreadPool: {t.IsThreadPoolThread}");
```
You'll see that the Apartment State is STA (single threaded apartment) as expected. After all, there is an [STAThread] attribute on the method! Now change the signature of the main method so that instead of returning 'void' it reads ' async Task' and run it again. Now the Apartment State is MTA (multi-threaded apartment). Yes, the [STAThread] attribute is still there, but it's ignored!

We would need a significant overhaul in order to make our PInvoke calls from an MTA thread. It's probably not something we have the resources to do. Perhaps one of the work-arounds in the article above will give you a clue as to how to get around this? I'm going to close this, but if you come up with a workable change we could implement without a major impact, please re-open and we'll try to work with you to get it done.

**Comment by Zaid-Ajaj** [comment]
Thanks a lot for investigating the issue so thoroughly! So I need to run the window always on the main thread. I'll see what I can do, maybe try running the backend in the background and the window on the main. There are simpler web servers that might allow me to do this easier.

Again, thanks a lot for looking into the problem, really appreciate it 😄

**Comment by Zaid-Ajaj** [comment]
@MikeYeager @philippjbauer Here are my experimentation results: a full stack F# application running inside a Photino window. Notice how hot module reloading works where I can change the UI without reloading the state 🤯 

See [Zaid-Ajaj/desktop-feliz-with-photino](https://github.com/Zaid-Ajaj/desktop-feliz-with-photino)

![photino-feliz](https://user-images.githubusercontent.com/13316248/110884505-7b23d680-82e5-11eb-9d07-3f5bc3db4845.gif)

The frontend is written in F# and compiled to JS using [Fable](https://fable.io). It uses React via the [Feliz library](https://github.com/Zaid-Ajaj/Feliz) and talks to the backend using type-safe RPC using [Fable.Remoting](https://github.com/Zaid-Ajaj/Fable.Remoting)

**Comment by MikeYeager** [comment]
That is really cool!

**Comment by Zaid-Ajaj** [comment]
@MikeYeager thanks! you can already play with it if you want. I plan on making a github template soon that includes build/release automation etc.

**Comment by theimowski** [comment]
FWIW I've managed to get Photino window running in a MTA by spinning up a new dedicated STA thread:

```fsharp
let thread = Thread(ThreadStart(fun() -> runPhotino()))
thread.SetApartmentState(ApartmentState.STA)
thread.Start()
```

(not sure if the above compiles, rewritten that by hand here)
