### ISSUE TITLE
SendWebMessage bug on v3.1.17

### ISSUE THREAD

**Issue by towerbit** [tryphotino/photino.NET#211]
There seems to be an issue where only the first character of the message string is returned by SendWebMessage() when the 'Call .NET' button is clicked in the Photino sample code (Photino.HelloPhotino.NET) on Windows 10, while running with Photino.NET v3.1.17. The sample code worked well with the last version I tried, which was Photino.NET 2.3.0.

**Comment by raddevus** [comment]
I just tried this on Ubuntu 22.04.4 LTS and on Windows 10.
I can confirm that it works properly on Ubuntu 22.04.4.
And, it does seem to only show the first character on Win10.
Here's a snapshot of the failure on Win10:
![image](https://github.com/user-attachments/assets/3a0b4b2d-d487-4b4f-aaee-bec83846cf68)

Just as the @towerbit  said, this is occuring when running Photino.NET v3.1.17

**Comment by MikeYeager** [comment]
@towerbit @raddevus Can you confirm that the sample project is targeting .NET 6?  If so, does it work if you change it to .NET 7 or .NET 8?

**Comment by towerbit** [comment]
It works properly on .NET 7 and .NET 8, but not on .NET 6.

**Comment by MikeYeager** [comment]
@towerbit Thanks for confirming. We were able to duplicate the issue and fix it, though we haven't posted a new version yet. It stems from how marshalling was dramatically changed in .NET 7 and 8. It should be working in .NET 6 with the next release. Until then, if you can compile for .NET 7 or 8 instead of 6 you can use that as a work-around.
