### ISSUE TITLE
[feature request] StartStringWide/StartString style of property very confuse to user

### ISSUE THREAD

**Issue by congzhangzh** [tryphotino/photino.NET#64]
Hi,

Is that possible to eliminate the use of *Wide Style property complete, even it's already internal?

a user just uses C# string like StartString, As for semantic level, the user just cares char.

maybe we can do this at #if level?

```c#

	internal struct PhotinoNativeParameters
	{
                #if WINDOWS
                [MarshalAs(UnmanagedType.LPUTF8Str)]
                #else
                [MarshalAs(UnmanagedType.LPWStr)]
                #endif
		internal string StartString;
      }
```

**Comment by congzhangzh** [comment]
https://github.com/tryphotino/photino.NET/blob/master/Photino.NET/PhotinoNativeParameters.cs#L9-L120
@MikeYeager

**Comment by philippjbauer** [comment]
Thank you for pointing this out @congzhangzh!

Unfortunately we ran into an issue compiling the Photino.NET project with the UnmanagedType selected by an if condition like you propose. The problem is that the system that it is compiled determines which type is used and breaks the compatibility on other systems. I.e. if it is built on Windows it will select the LPWStr that is compatible with Windows and breaks the Photino.NET assembly for macOS and Linux and vice versa. We ended up settling for this solution because we found no other way to make sure that the correct string type was used on each respective operating system.

**Comment by theolivenbaum** [comment]
@philippjbauer can you use the OperatingSystem.IsWindows() and similar flags to decide which struct to use instead and hide this from the user?

**Comment by congzhangzh** [comment]
Hi philippjbauer,

Maybe I do not  show my full idea, except ifdef on .net part, the ifdef on native part is need too:)

Some more if define need on the native part too,
https://github.com/tryphotino/photino.Native/blob/cdec0aa80ee878cb0aa95869e5258dee4c44ace9/Photino.Native/Photino.h#L45-L87
