### ISSUE TITLE
Cannot load static files macOS

### ISSUE THREAD

**Issue by TheOnlyBeardedBeast** [tryphotino/photino.NET#70]
I have built a react project and I cant load it in photino

OS: macOS
photino.net version: 2.0.13

<img width="791" alt="Screenshot 2021-10-16 at 23 38 56" src="https://user-images.githubusercontent.com/55414686/137602773-e1dadeab-cfea-410d-a20b-b7e1b0d1cd66.png">

Source files: https://github.com/TheOnlyBeardedBeast/PhotinoFetch/tree/master/HelloPhotino/HelloPhotino

**Comment by TheOnlyBeardedBeast** [comment]
@philippjbauer Hi, any news?

**Comment by MikeYeager** [comment]
@TheOnlyBeardedBeast We took a look at your source code and we believe the issue is the browser control trying to load the script from the local hard drive because of this line:    ` <script type="module" src="/assets/index.d02e89bc.js"></script>`
All browsers consider this unsafe and we're not even sure this security setting can be turned off any more. With the full browser, you could, in that past at least, start the browser with a parameter to disable it. That's why in all of our samples, we inject the JavaScript code or embed it in the HTML file. Another possibility is to run a local web server to serve the files instead of reading them from disk.

**Comment by TheOnlyBeardedBeast** [comment]
@MikeYeager thank you, I will try out to load the static files differently.
